# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-22 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoros', '0004_auto_20190722_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='children.jpg', upload_to='pics/'),
        ),
    ]
