# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-23 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phoros', '0007_image_post_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_date',
        ),
    ]
